# Generated by Django 4.2.27 on 2026-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', help_text='Lucide图标名称', max_length=50, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('doc', '文档'), ('video', '视频'), ('archive', '压缩包'), ('link', '链接'), ('other', '其他')], default='other', max_length=10, verbose_name='类型'),
        ),
    ]
