# Generated by Django 4.2.27 on 2026-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_icon_resource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', max_length=50, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ai_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='AI标签'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='embedding_text',
            field=models.TextField(blank=True, null=True, verbose_name='向量文本'),
        ),
    ]
