# Generated by Django 4.2.27 on 2026-01-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_category_icon_alter_resource_ai_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '资源分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='views',
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('doc', '文档'), ('video', '视频'), ('archive', '压缩包'), ('link', '链接'), ('other', '其他')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已发布')], default='approved', max_length=10),
        ),
        migrations.CreateModel(
            name='DesktopIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, verbose_name='显示名称')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('is_shortcut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons_inside', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_icons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
