# Generated by Django 4.2.27 on 2026-01-27 02:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.resource_directory_path, verbose_name='资源文件'),
        ),
    ]
