# Generated by Django 4.2.27 on 2026-01-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='图标类名'),
        ),
    ]
