# Generated by Django 4.2.27 on 2026-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resource_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('doc', '文档'), ('video', '视频'), ('image', '图片'), ('audio', '音频'), ('archive', '压缩包'), ('link', '链接'), ('other', '其他')], default='other', max_length=10),
        ),
    ]
