# Generated by Django 4.2.27 on 2026-01-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resource_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('link', models.URLField(verbose_name='链接')),
                ('link_type', models.CharField(choices=[('h5', 'H5应用'), ('video', '视频链接'), ('doc', '文章/文档'), ('image', '图片集'), ('other', '其他')], default='h5', max_length=10, verbose_name='类型')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='app_covers/')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标类名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已上架'), ('rejected', '已拒绝')], default='pending', max_length=10)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用条目',
            },
        ),
        migrations.CreateModel(
            name='AppTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '应用标签',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='desktopicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='租户名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='租户标识')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '租户',
            },
        ),
        migrations.CreateModel(
            name='AppView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.appentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用浏览',
            },
        ),
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾信息'), ('copyright', '侵权'), ('abuse', '恶意内容'), ('other', '其他')], default='other', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.appentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用举报',
            },
        ),
        migrations.AddField(
            model_name='appentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='apps', to='core.apptag'),
        ),
        migrations.AddField(
            model_name='appentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_entries', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='AppComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.appentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用评论',
            },
        ),
        migrations.CreateModel(
            name='AppCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='专题标题')),
                ('description', models.TextField(blank=True, verbose_name='专题描述')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.tenant')),
            ],
            options={
                'verbose_name': '专题合集',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='desktopicon',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desktop_icons', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='SyncPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_enabled', models.BooleanField(default=False)),
                ('conflict_strategy', models.CharField(choices=[('server_wins', '以云端为准'), ('client_wins', '以本地为准')], default='server_wins', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_preferences', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '同步偏好',
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '租户管理员'), ('member', '普通成员'), ('viewer', '访客')], default='member', max_length=10, verbose_name='成员角色')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成员关系',
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='AppLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.appentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用点赞',
                'unique_together': {('user', 'app')},
            },
        ),
        migrations.CreateModel(
            name='AppCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='core.appentry')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.appcollection')),
            ],
            options={
                'verbose_name': '专题条目',
                'unique_together': {('collection', 'app')},
            },
        ),
    ]
